### ISSUE TITLE
Add support for bulk conversion

### ISSUE THREAD

**Issue by JacobDB** [rizqirizqi/webpconvert#154]
This works great for one-by-one, but it'd be nice to be able to do a whole folder at once

**Comment by rizqirizqi** [comment]
Hi @JacobDB, you can use webpconvert for a whole folder like this:
```
npx webpconvert folder-name
```

But I think the current code is only converting the files inside one folder. Did you mean to add support for a whole folder recursively? That's a good idea!

**Comment by 3xploiton3** [comment]
> Hi @JacobDB, you can use webpconvert for a whole folder like this:
> 
> ```
> npx webpconvert folder-name
> ```
> 
> But I think the current code is only converting the files inside one folder. Did you mean to add support for a whole folder recursively? That's a good idea!

Bro, can you make this recursively as optional?
should be respect only convert files in folder,

you can use
-r | recursively | convert include sub-folder

**Comment by rizqirizqi** [comment]
aah that's right, it should be optional
