### ISSUE TITLE
dont include rename the extension

### ISSUE THREAD

**Issue by 3xploiton3** [rizqirizqi/webpconvert#195]
by default webpconvert, rename files include extension jpg/png, shouldn't be 

![image](https://github.com/rizqirizqi/webpconvert/assets/19517680/1cd0e26e-a95b-401c-b695-1bdadf867b06)

**Comment by rizqirizqi** [comment]
If I do this, it will be a breaking change. It would be better if we planned this for v4. But is it really necessary to omit the previous extension? Or the previous extension is important and needs to be kept? Wdyt? :thinking:

**Comment by 3xploiton3** [comment]
give us optional setting, by default doesn't add or remove name original files,

**Comment by donato21** [comment]
Hi, jumping in to say that for my usecase, I need to type out the file names into a config and having the .jpg.webp is an inconvenience. For now I'll make a python script rename them but it'd be nice to have the original extension removed by default.

**Comment by rizqirizqi** [comment]
oh okay then, looks like it's better to make it optional, I will remove the original extension on v4 release
